//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB43
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentResult
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int QuestionId { get; set; }
        public System.DateTime EvalutionDate { get; set; }
        public string Ans { get; set; }
        public double Marks { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
